---
# Regular user operation
- name: Create internal network
  openstack.cloud.network:
     cloud: "{{ cloud }}"
     state: present
     name: "{{ network_name }}"
     external: false
  register: internal_net

- name: Ensure router doesn't exist before tests
  openstack.cloud.router:
     cloud: "{{ cloud }}"
     state: absent
     name: "{{ router_name }}"

- name: Get ports in internal network
  openstack.cloud.port_info:
    cloud: "{{ cloud }}"
    filters:
      network_id: "{{ internal_net.id }}"
  register: existing_ports

- name: Ensure ports don't exist before tests
  openstack.cloud.port:
    cloud: "{{ cloud }}"
    name: "{{ item.id }}"
    state: absent
  loop: "{{ existing_ports.ports }}"

- name: Delete subnets before tests
  openstack.cloud.subnet:
    cloud: "{{ cloud }}"
    state: absent
    name: "{{ item.name }}"
  loop: "{{ test_subnets }}"

- name: Create subnets 1-4
  openstack.cloud.subnet: "{{ item }}"
  loop: "{{ test_subnets }}"

- name: Create router
  openstack.cloud.router:
     cloud: "{{ cloud }}"
     state: present
     name: "{{ router_name }}"
  register: result

- name: Verify returned values
  assert:
    that:
      - item in result.router
  loop: "{{ expected_fields }}"

- name: Update router (add interface)
  openstack.cloud.router:
     cloud: "{{ cloud }}"
     state: present
     name: "{{ router_name }}"
     interfaces:
         - shade_subnet1

- name: Update router (add interface) again
  openstack.cloud.router:
     cloud: "{{ cloud }}"
     state: present
     name: "{{ router_name }}"
     interfaces:
         - shade_subnet1
  register: result

- name: Assert idempotent module
  assert:
    that: result is not changed

- name: Gather routers info
  openstack.cloud.routers_info:
     cloud: "{{ cloud }}"
     name: "{{ router_name }}"
     filters:
       admin_state_up: true
  register: result

- name: Verify routers info
  assert:
    that:
      - "result.routers.0.name == router_name"
      - (result.routers.0.interfaces_info|length) == 1

- name: Verify existence of return values
  assert:
    that:
      - item in result.routers[0]
  loop: "{{ expected_fields + ['interfaces_info'] }}"

- name: Gather routers info with filters
  openstack.cloud.routers_info:
      cloud: "{{ cloud }}"
      filters:
        admin_state_up: true
        name: "{{ router_name }}"
  register: result_filter

- name: Verify routers info with filter
  assert:
    that:
      - "result_filter.routers.0.name == router_name"
      - (result_filter.routers.0.interfaces_info|length) == 1

- name: Update router (change interfaces)
  openstack.cloud.router:
     cloud: "{{ cloud }}"
     state: present
     name: "{{ router_name }}"
     interfaces:
         - net: '{{ network_name }}'
           subnet: shade_subnet2
           portip: 10.8.8.1
         - net: '{{ network_name }}'
           subnet: shade_subnet3
         - shade_subnet4

- name: Update router (change interfaces) again
  openstack.cloud.router:
     cloud: "{{ cloud }}"
     state: present
     name: "{{ router_name }}"
     interfaces:
         - net: '{{ network_name }}'
           subnet: shade_subnet2
           portip: 10.8.8.1
         - net: '{{ network_name }}'
           subnet: shade_subnet3
         - shade_subnet4
  register: result

- name: Assert idempotent module
  assert:
    that: result is not changed

- name: Gather routers info
  openstack.cloud.routers_info:
     cloud: "{{ cloud }}"
     name: "{{ router_name }}"
     filters:
       is_admin_state_up: true
  register: result

- name: Verify routers info
  assert:
    that:
      - "result.routers.0.name == router_name"
      - (result.routers.0.interfaces_info|length) == 3
      - result.routers.0.interfaces_info|map(attribute='ip_address')|sort|list ==
        ['10.10.10.1', '10.8.8.1', '10.9.9.1']

- name: Update router (remove interface)
  openstack.cloud.router:
     cloud: "{{ cloud }}"
     state: present
     name: "{{ router_name }}"
     interfaces:
         - net: '{{ network_name }}'
           subnet: shade_subnet1
           portip: 10.7.7.1

- name: Update router (remove interface) again
  openstack.cloud.router:
     cloud: "{{ cloud }}"
     state: present
     name: "{{ router_name }}"
     interfaces:
         - net: '{{ network_name }}'
           subnet: shade_subnet1
           portip: 10.7.7.1
  register: result

- name: Assert idempotent module
  assert:
    that: result is not changed

- name: Gather routers info
  openstack.cloud.routers_info:
     cloud: "{{ cloud }}"
     name: "{{ router_name }}"
     filters:
       is_admin_state_up: true
  register: result

- name: Verify routers info
  assert:
    that:
      - "result.routers.0.name == router_name"
      - (result.routers.0.interfaces_info|length) == 1
      - result.routers.0.interfaces_info.0.ip_address == '10.7.7.1'

# Admin operation
- name: Create external network
  openstack.cloud.network:
     cloud: "{{ cloud }}"
     state: present
     name: "{{ external_network_name }}"
     external: "{{ network_external }}"
  when:
    - network_external

- name: Create subnet5
  openstack.cloud.subnet:
     cloud: "{{ cloud }}"
     state: present
     network_name: "{{ external_network_name }}"
     name: shade_subnet5
     cidr: 10.6.6.0/24
  when:
    - network_external

- name: Update router (add external gateway)
  openstack.cloud.router:
     cloud: "{{ cloud }}"
     state: present
     name: "{{ router_name }}"
     network: "{{ external_network_name }}"
     interfaces:
         - shade_subnet1
  when:
    - network_external

- name: Gather routers info
  openstack.cloud.routers_info:
     cloud: "{{ cloud }}"
     name: "{{ router_name }}"
     filters:
       admin_state_up: true
  register: result

- name: Verify routers info
  assert:
    that:
      - "result.routers.0.name == router_name"
      - (result.routers.0.interfaces_info|length) == 1

- name: Update router (change external fixed ips)
  openstack.cloud.router:
     cloud: "{{ cloud }}"
     state: present
     name: "{{ router_name }}"
     interfaces:
         - shade_subnet1
     network: "{{ external_network_name }}"
     external_fixed_ips:
        - subnet: shade_subnet5
          ip: 10.6.6.100
  when:
    - network_external

- name: Gather routers info
  openstack.cloud.routers_info:
     cloud: "{{ cloud }}"
     name: "{{ router_name }}"
     filters:
       admin_state_up: true
  register: result

- name: Verify routers info
  assert:
    that:
      - "result.routers.0.name == router_name"
      - (result.routers.0.external_gateway_info.external_fixed_ips|length) == 1
      - result.routers.0.external_gateway_info.external_fixed_ips.0.ip_address == "10.6.6.100"
  when:
    - network_external

- name: Update router (add external fixed ips)
  openstack.cloud.router:
     cloud: "{{ cloud }}"
     state: present
     name: "{{ router_name }}"
     interfaces:
         - shade_subnet1
     external_gateway_info:
        network: "{{ external_network_name }}"
        external_fixed_ips:
           - subnet: shade_subnet5
             ip: 10.6.6.100
           - subnet: shade_subnet5
             ip: 10.6.6.101
  when:
    - network_external

- name: Update router (add external fixed ips) again
  openstack.cloud.router:
     cloud: "{{ cloud }}"
     state: present
     name: "{{ router_name }}"
     interfaces:
         - shade_subnet1
     network: "{{ external_network_name }}"
     external_fixed_ips:
        - subnet: shade_subnet5
          ip: 10.6.6.100
        - subnet: shade_subnet5
          ip: 10.6.6.101
  when:
    - network_external
  register: result

- name: Assert idempotent module
  assert:
    that: result is not changed

- name: Gather routers info
  openstack.cloud.routers_info:
     cloud: "{{ cloud }}"
     name: "{{ router_name }}"
     filters:
       admin_state_up: true
  register: result

- name: Verify routers info
  assert:
    that:
      - "result.routers.0.name == router_name"
      - (result.routers.0.external_gateway_info.external_fixed_ips|length) == 2
      - result.routers.0.external_gateway_info.external_fixed_ips|map(attribute='ip_address')|sort|list ==
        ["10.6.6.100", "10.6.6.101"]
  when:
    - network_external

- name: Update router (remove external fixed ips)
  openstack.cloud.router:
     cloud: "{{ cloud }}"
     state: present
     name: "{{ router_name }}"
     interfaces:
         - shade_subnet1
     network: "{{ external_network_name }}"
     external_fixed_ips:
        - subnet: shade_subnet5
          ip: 10.6.6.101
  when:
    - network_external

- name: Update router (remove external fixed ips) again
  openstack.cloud.router:
     cloud: "{{ cloud }}"
     state: present
     name: "{{ router_name }}"
     interfaces:
         - shade_subnet1
     network: "{{ external_network_name }}"
     external_fixed_ips:
        - subnet: shade_subnet5
          ip: 10.6.6.101
  when:
    - network_external
  register: result

- name: Assert idempotent module
  assert:
    that: result is not changed

- name: Gather routers info
  openstack.cloud.routers_info:
     cloud: "{{ cloud }}"
     name: "{{ router_name }}"
     filters:
       admin_state_up: true
  register: result

- name: Verify routers info
  assert:
    that:
      - "result.routers.0.name == router_name"
      - (result.routers.0.external_gateway_info.external_fixed_ips|length) == 1
      - result.routers.0.external_gateway_info.external_fixed_ips.0.ip_address == "10.6.6.101"
  when:
    - network_external

- name: Update router (disable external snat)
  openstack.cloud.router:
     cloud: "{{ cloud }}"
     state: present
     name: "{{ router_name }}"
     enable_snat: false
     interfaces:
         - shade_subnet1
     network: "{{ external_network_name }}"
     external_fixed_ips:
        - subnet: shade_subnet5
          ip: 10.6.6.101
  when:
    - network_external
  register: result

- name: Gather routers info
  openstack.cloud.routers_info:
     cloud: "{{ cloud }}"
     name: "{{ router_name }}"
     filters:
       admin_state_up: true
  register: result
- name: Verify routers info
  assert:
    that:
      - "result.routers.0.name == router_name"
      - "not result.routers.0.external_gateway_info.enable_snat"
  when:
    - network_external

- name: Update router (disable external snat) again
  openstack.cloud.router:
     cloud: "{{ cloud }}"
     state: present
     name: "{{ router_name }}"
     enable_snat: false
     interfaces:
         - shade_subnet1
     network: "{{ external_network_name }}"
     external_fixed_ips:
        - subnet: shade_subnet5
          ip: 10.6.6.101
  when:
    - network_external
  register: result

- name: Assert idempotent module
  assert:
    that: result is not changed

- name: Delete router
  openstack.cloud.router:
     cloud: "{{ cloud }}"
     state: absent
     name: "{{ router_name }}"

- name: Delete router again
  openstack.cloud.router:
     cloud: "{{ cloud }}"
     state: absent
     name: "{{ router_name }}"
  register: result

- name: Assert idempotent module
  assert:
    that: result is not changed

- name: Create router with simple interface
  openstack.cloud.router:
     cloud: "{{ cloud }}"
     state: present
     name: "{{ router_name }}"
     interfaces:
         - shade_subnet1
  register: result

- name: Assert changed
  assert:
    that: result is changed

- name: Set portip in already assigned subnet
  openstack.cloud.router:
     cloud: "{{ cloud }}"
     state: present
     name: "{{ router_name }}"
     interfaces:
         - subnet: shade_subnet1
           net: "{{ network_name }}"
           portip: 10.7.7.42
  register: result

- name: Assert changed
  assert:
    that: result is changed

- name: Gather routers info
  openstack.cloud.routers_info:
     cloud: "{{ cloud }}"
     name: "{{ router_name }}"
  register: result

- name: Verify routers info
  assert:
    that: "'10.7.7.42' in result.routers[0].interfaces_info|map(attribute='ip_address')"

- name: Unset portip in already assigned subnet
  openstack.cloud.router:
     cloud: "{{ cloud }}"
     state: present
     name: "{{ router_name }}"
     interfaces:
         - subnet: shade_subnet1
           net: "{{ network_name }}"
  register: result

- name: Assert not changed
  assert:
    that: result is not changed

- name: Delete router
  openstack.cloud.router:
     cloud: "{{ cloud }}"
     state: absent
     name: "{{ router_name }}"

- name: Get ports in internal network
  openstack.cloud.port_info:
    cloud: "{{ cloud }}"
    filters:
      network_id: "{{ internal_net.id }}"
  register: existing_ports

- name: Clean up ports
  openstack.cloud.port:
    cloud: "{{ cloud }}"
    name: "{{ item.id }}"
    state: absent
  loop: "{{ existing_ports.ports }}"

- name: Delete subnet5
  openstack.cloud.subnet:
     cloud: "{{ cloud }}"
     state: absent
     name: shade_subnet5
  when:
    - network_external

- name: Delete subnets 1-4
  openstack.cloud.subnet:
    cloud: "{{ cloud }}"
    state: absent
    name: "{{ item.name }}"
  loop: "{{ test_subnets }}"

- name: Delete internal network
  openstack.cloud.network:
     cloud: "{{ cloud }}"
     state: absent
     name: "{{ network_name }}"

- name: Delete external network
  openstack.cloud.network:
     cloud: "{{ cloud }}"
     state: absent
     name: "{{ external_network_name }}"
  when:
    - network_external
