---
- name: Ensure security group does not exist before tests
  openstack.cloud.security_group:
     cloud: "{{ cloud }}"
     name: "{{ secgroup_name }}"
     state: absent
     description: Created from Ansible playbook

- name: Create security group
  openstack.cloud.security_group:
     cloud: "{{ cloud }}"
     name: "{{ secgroup_name }}"
     state: present
     description: Created from Ansible playbook

- name: List all security groups of a project
  openstack.cloud.security_group_info:
     cloud: "{{ cloud }}"
  register: test_sec_groups

- name: Check - List all security groups of a project
  assert:
    that:
      - test_sec_groups.security_groups | length > 0

- name: Filter security group by name
  openstack.cloud.security_group_info:
     cloud: "{{ cloud }}"
     name: "{{ secgroup_name }}"
  register: test_sec_group

- name: Check - List all security groups of a project
  assert:
    that:
      - test_sec_group.security_groups | length  == 1
      - test_sec_group.security_groups[0]['name'] == secgroup_name
  # This fails on Stein only
  when: sdk_version is version("0.36.5", '>=')

- name: Delete security group
  openstack.cloud.security_group:
     cloud: "{{ cloud }}"
     name: "{{ secgroup_name }}"
     state: absent
