---
- name: List admin project
  openstack.cloud.project_info:
    cloud: "{{ cloud }}"
    name: 'admin'
  register: project_admin

- name: List admin project with filter
  openstack.cloud.project_info:
    cloud: "{{ cloud }}"
    filters:
      name: 'admin'

- name: Check output of list admin project
  assert:
    that:
      - project_admin.openstack_projects | length == 1

- name: List all projects
  openstack.cloud.project_info:
    cloud: "{{ cloud }}"
  register: all_projects

- name: Check output of list all projects
  assert:
    that:
      - all_projects.openstack_projects | length > 0

- name: List admin project with domain
  openstack.cloud.project_info:
    cloud: "{{ cloud }}"
    name: 'admin'
    domain: 'default'
  register: project_domain

- name: Check output of list admin project with admin domain
  assert:
    that:
      - project_domain.openstack_projects | length == 1

- name: Assert fields on SDK 1.*
  assert:
    that:
      - '["description", "domain_id", "is_domain", "is_enabled", "options",
          "parent_id", "id", "name", "tags"] |
          difference(project_admin.openstack_projects.0.keys()) | length == 0'
