---
- name: Trigger flavor listing to create logs
  openstack.cloud.compute_flavor_info:
    cloud: "{{ cloud }}"
    sdk_log_path: "{{ sdk_log_file_path }}"
    sdk_log_level: "DEBUG"

- name: Read openstacksdk's log file
  ansible.builtin.slurp:
    src: "{{ sdk_log_file_path }}"
  register: log

- name: Print contents of openstacksdk's log
  ansible.builtin.debug:
    msg: "{{ log['content'] | b64decode }}"
