expected_fields:
  - allocation_id
  - bios_interface
  - boot_interface
  - boot_mode
  - chassis_id
  - clean_step
  - conductor
  - conductor_group
  - console_interface
  - created_at
  - deploy_interface
  - deploy_step
  - driver
  - driver_info
  - driver_internal_info
  - extra
  - fault
  - id
  - inspect_interface
  - instance_id
  - instance_info
  - is_automated_clean_enabled
  - is_console_enabled
  - is_maintenance
  - is_protected
  - is_retired
  - is_secure_boot
  - last_error
  - links
  - maintenance_reason
  - management_interface
  - name
  - network_interface
  - owner
  - port_groups
  - ports
  - power_interface
  - power_state
  - properties
  - protected_reason
  - provision_state
  - raid_config
  - raid_interface
  - rescue_interface
  - reservation
  - resource_class
  - retired_reason
  - states
  - storage_interface
  - target_power_state
  - target_provision_state
  - target_raid_config
  - traits
  - updated_at
  - vendor_interface
