---
- name: Getting info about allocated ips
  openstack.cloud.floating_ip_info:
    cloud: "{{ cloud }}"
  register: fips

- name: assert result
  assert:
    that:
      - fips is success
      - fips is not changed

- name: assert fields
  when: fips.floating_ips|length > 0
  assert:
    that:
      # allow new fields to be introduced but prevent fields from being removed
      - '["created_at", "description", "dns_domain", "dns_name", "fixed_ip_address", "floating_ip_address",
          "floating_network_id", "id", "name", "port_details", "port_id", "project_id", "qos_policy_id",
          "revision_number", "router_id", "status", "subnet_id", "tags", "updated_at"]|
          difference(fips.floating_ips.0.keys())|length == 0'
