---
- name: List all ports
  openstack.cloud.port_info:
    cloud: "{{ cloud }}"
  register: result_all

- name: Assert fields
  assert:
    that:
      - item in result_all.ports.0
  loop:
    - allowed_address_pairs
    - binding_host_id
    - binding_profile
    - binding_vif_details
    - binding_vif_type
    - binding_vnic_type
    - created_at
    - data_plane_status
    - description
    - device_id
    - device_owner
    - device_profile
    - dns_assignment
    - dns_domain
    - dns_name
    - extra_dhcp_opts
    - fixed_ips
    - id
    - ip_allocation
    - is_admin_state_up
    - is_port_security_enabled
    - mac_address
    - name
    - network_id
    - numa_affinity_policy
    - project_id
    - propagate_uplink_status
    - qos_network_policy_id
    - qos_policy_id
    - resource_request
    - revision_number
    - security_group_ids
    - status
    - tags
    - tenant_id
    - trunk_details
    - updated_at

- name: Get port by id
  openstack.cloud.port_info:
    cloud: "{{ cloud }}"
    port: "{{ result_all.ports[0].id }}"
  register: result_id

- name: Assert results by id
  assert:
    that:
      - item.id == result_all.ports[0].id
  loop: "{{ result_id.ports }}"

- name: List port with device_id filter
  openstack.cloud.port_info:
    cloud: "{{ cloud }}"
    filters:
      device_id: "{{ result_all.ports[0].device_id }}"
  register: result_filter

- name: Assert port was returned
  assert:
    that:
      - result_filter.ports | length >= 1
